server:
  port: 1111
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}