server:
  port: 1111
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}